# Generated by Django 2.0.10 on 2019-05-03 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineSchool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=30, verbose_name='学校名称')),
                ('province_name', models.CharField(max_length=30, verbose_name='省份名称')),
                ('school_type', models.CharField(max_length=30, verbose_name='办学类型')),
                ('type_name', models.CharField(max_length=30, verbose_name='院校类型')),
                ('admissions', models.CharField(blank=True, max_length=30, verbose_name='自主招生')),
                ('central', models.CharField(blank=True, max_length=30, verbose_name='中央部委')),
                ('department', models.CharField(blank=True, max_length=30, verbose_name='教育部直属')),
                ('f211', models.CharField(blank=True, max_length=30, verbose_name='211')),
                ('f985', models.CharField(blank=True, max_length=30, verbose_name='985')),
                ('dual_class', models.CharField(blank=True, max_length=30, verbose_name='双一流')),
                ('dual_class_name', models.CharField(blank=True, max_length=30, verbose_name='双一流名称')),
                ('type', models.CharField(blank=True, max_length=30, verbose_name='文理科')),
                ('batch', models.CharField(blank=True, max_length=30, verbose_name='批次')),
                ('local_province_name', models.CharField(blank=True, max_length=30, verbose_name='招生省份')),
                ('year', models.CharField(blank=True, max_length=30, verbose_name='年份')),
                ('max_score', models.CharField(blank=True, max_length=30, verbose_name='最高分')),
                ('min_score', models.CharField(blank=True, max_length=30, verbose_name='最低分')),
                ('average', models.CharField(blank=True, max_length=30, verbose_name='平均分')),
                ('proscore', models.CharField(blank=True, max_length=30, verbose_name='省控线')),
            ],
            options={
                'verbose_name': '学校录取分数线',
                'verbose_name_plural': '学校录取分数线',
            },
        ),
        migrations.CreateModel(
            name='LineSpecialty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sp_name', models.CharField(max_length=30, verbose_name='专业名称')),
                ('school_name', models.CharField(max_length=30, verbose_name='学校名称')),
                ('level1_name', models.CharField(max_length=30, verbose_name='专业层次')),
                ('level2_name', models.CharField(max_length=30, verbose_name='专业门类')),
                ('level3_name', models.CharField(max_length=30, verbose_name='专业类别')),
                ('province_name', models.CharField(max_length=30, verbose_name='省份名称')),
                ('school_type', models.CharField(max_length=30, verbose_name='办学类型')),
                ('type_name', models.CharField(max_length=30, verbose_name='院校类型')),
                ('admissions', models.CharField(blank=True, max_length=30, verbose_name='自主招生')),
                ('central', models.CharField(blank=True, max_length=30, verbose_name='中央部委')),
                ('department', models.CharField(blank=True, max_length=30, verbose_name='教育部直属')),
                ('f211', models.CharField(blank=True, max_length=30, verbose_name='211')),
                ('f985', models.CharField(blank=True, max_length=30, verbose_name='985')),
                ('dual_class', models.CharField(blank=True, max_length=30, verbose_name='双一流')),
                ('dual_class_name', models.CharField(blank=True, max_length=30, verbose_name='双一流名称')),
                ('type', models.CharField(blank=True, max_length=30, verbose_name='文理科')),
                ('batch', models.CharField(blank=True, max_length=30, verbose_name='批次')),
                ('local_province_name', models.CharField(blank=True, max_length=30, verbose_name='招生省份')),
                ('year', models.CharField(blank=True, max_length=30, verbose_name='年份')),
                ('max_score', models.CharField(blank=True, max_length=30, verbose_name='最高分')),
                ('min_score', models.CharField(blank=True, max_length=30, verbose_name='最低分')),
                ('average', models.CharField(blank=True, max_length=30, verbose_name='平均分')),
                ('proscore', models.CharField(blank=True, max_length=30, verbose_name='省控线')),
            ],
            options={
                'verbose_name': '专业录取分数线',
                'verbose_name_plural': '专业录取分数线',
            },
        ),
        migrations.RenameField(
            model_name='linepro',
            old_name='average',
            new_name='proscore',
        ),
        migrations.AlterField(
            model_name='schoolinfo',
            name='province_name',
            field=models.CharField(max_length=30, verbose_name='省份名称'),
        ),
        migrations.AlterField(
            model_name='specialtyinfo',
            name='level3_name',
            field=models.CharField(max_length=30, verbose_name='专业类别'),
        ),
    ]
