# Generated by Django 2.0.10 on 2019-05-12 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='linepro',
            options={'ordering': ['id'], 'verbose_name': '省份录取分数线', 'verbose_name_plural': '省份录取分数线'},
        ),
        migrations.AlterModelOptions(
            name='lineschool',
            options={'ordering': ['id'], 'verbose_name': '学校录取分数线', 'verbose_name_plural': '学校录取分数线'},
        ),
        migrations.AlterModelOptions(
            name='linespecialty',
            options={'ordering': ['id'], 'verbose_name': '专业录取分数线', 'verbose_name_plural': '专业录取分数线'},
        ),
        migrations.AlterModelOptions(
            name='schoolinfo',
            options={'ordering': ['id'], 'verbose_name': '学校信息', 'verbose_name_plural': '学校信息'},
        ),
        migrations.AlterModelOptions(
            name='specialtyinfo',
            options={'ordering': ['id'], 'verbose_name': '专业信息', 'verbose_name_plural': '专业信息'},
        ),
        migrations.AlterField(
            model_name='linespecialty',
            name='admissions',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='自主招生'),
        ),
        migrations.AlterField(
            model_name='linespecialty',
            name='central',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='中央部委'),
        ),
        migrations.AlterField(
            model_name='linespecialty',
            name='department',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='教育部直属'),
        ),
    ]
