# Generated by Django 2.0.10 on 2019-05-03 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0002_auto_20190503_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialtyinfo',
            name='content',
            field=models.TextField(blank=True, verbose_name='专业简介'),
        ),
        migrations.AlterField(
            model_name='specialtyinfo',
            name='degree',
            field=models.CharField(blank=True, max_length=30, verbose_name='授予学士'),
        ),
        migrations.AlterField(
            model_name='specialtyinfo',
            name='do_what',
            field=models.TextField(blank=True, verbose_name='干什么'),
        ),
        migrations.AlterField(
            model_name='specialtyinfo',
            name='is_what',
            field=models.TextField(blank=True, verbose_name='是什么'),
        ),
        migrations.AlterField(
            model_name='specialtyinfo',
            name='job',
            field=models.TextField(blank=True, verbose_name='发展'),
        ),
        migrations.AlterField(
            model_name='specialtyinfo',
            name='learn_what',
            field=models.TextField(blank=True, verbose_name='学习什么'),
        ),
        migrations.AlterField(
            model_name='specialtyinfo',
            name='level1_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='专业层次'),
        ),
        migrations.AlterField(
            model_name='specialtyinfo',
            name='level2_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='专业门类'),
        ),
        migrations.AlterField(
            model_name='specialtyinfo',
            name='level3_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='专业类别'),
        ),
        migrations.AlterField(
            model_name='specialtyinfo',
            name='limit_year',
            field=models.CharField(blank=True, max_length=30, verbose_name='专业学习年份'),
        ),
        migrations.AlterField(
            model_name='specialtyinfo',
            name='rate',
            field=models.CharField(blank=True, max_length=30, verbose_name='男女比例'),
        ),
        migrations.AlterField(
            model_name='specialtyinfo',
            name='sel_adv',
            field=models.CharField(blank=True, max_length=30, verbose_name='生源选择'),
        ),
        migrations.AlterField(
            model_name='specialtyinfo',
            name='sp_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='专业名称'),
        ),
    ]
