# Generated by Django 2.0.10 on 2019-05-12 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0003_auto_20190512_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linespecialty',
            name='level1_name',
            field=models.CharField(max_length=30, null=True, verbose_name='专业层次'),
        ),
        migrations.AlterField(
            model_name='linespecialty',
            name='level2_name',
            field=models.CharField(max_length=30, null=True, verbose_name='专业门类'),
        ),
        migrations.AlterField(
            model_name='linespecialty',
            name='level3_name',
            field=models.CharField(max_length=30, null=True, verbose_name='专业类别'),
        ),
        migrations.AlterField(
            model_name='linespecialty',
            name='province_name',
            field=models.CharField(max_length=30, null=True, verbose_name='省份名称'),
        ),
        migrations.AlterField(
            model_name='linespecialty',
            name='school_name',
            field=models.CharField(max_length=30, null=True, verbose_name='学校名称'),
        ),
    ]
