# Generated by Django 2.0.10 on 2019-05-25 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0005_auto_20190525_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linespecialty',
            name='sp_name',
            field=models.CharField(max_length=80, verbose_name='专业名称'),
        ),
    ]
